services:
  web:
    container_name: isthatoutyet-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
  db:
    container_name: isthatoutyet-db
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    restart: always
