  # Include if you are self hosting or testing with a local database
services:
  db:
    container_name: isthatoutyet-db
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data