### GET request to example server
GET http://localhost:3000/api/route/
###

# ### Example
#     name: z.string(),
#     image: z.string().optional(),
#     score: z.number().min(0).max(100).optional(),
#     genre: z.string().optional(),
#     description: z.string().optional(),
#     price: z.number().optional(),
#     sale_price: z.number().optional(),
#     onSale: z.boolean().optional(),
#     storeUrl: z.string().optional(),
#     boxArtUrl: z.string().optional(),
#     releases: ReleaseObject.array().optional(),
#     datePublished: z.date().optional(),
###

### Send POST request with json body
POST http://localhost:3000/api/load/
Content-Type: application/json

{
        "name": "Mario & Luigi: Brothership",
        "image": "imageurl",
        "description": "descritpion goes here",
        "price": 10,
        "sale_price": 5,
        "onSale": true,
        "storeUrl": "https://www.amazon.com/Mario-Luigi-Brothership-Nintendo-Switch/dp/B07W39854Y/ref=sr_1_2?dchild=1&keywords=mario+brothership&qid=1633366666&q=mario+brothership&s=videogames&sr=1-2",
        "Box Art": "https://img.opencritic.com/game/undefined/EOhy6JbD.jpg",
        "datePublished": "Nov 7, 2024"
 }

### Send POST request with multiple objects ###
POST http://localhost:3000/api/load/
Content-Type: application/json

[
  {
        "name": "Mario & Luigi: Brothership",
        "image": "imageurl",
        "description": "descritpion goes here",
        "price": 10,
        "sale_price": 5,
        "onSale": true,
        "storeUrl": "https://www.amazon.com/Mario-Luigi-Brothership-Nintendo-Switch/dp/B07W39854Y/ref=sr_1_2?dchild=1&keywords=mario+brothership&qid=1633366666&q=mario+brothership&s=videogames&sr=1-2",
        "datePublished": "Nov 7, 2024"
  },
  {
        "name": "BattleStar Galatricas",
        "description": "descritpion goes here",
        "price": 10,
        "sale_price": 5,
        "onSale": true,
        "storeUrl": "https://www.amazon.com/Mario-Luigi-Brothership-Nintendo-Switch/dp/B07W39854Y/ref=sr_1_2?dchild=1&keywords=mario+brothership&qid=1633366666&q=mario+brothership&s=videogames&sr=1-2",
        "datePublished": "Nov 7, 2024"
  }
]
