name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Upload the Docker image to the container registry
      id: container_registry_upload
      uses: mr-smithers-excellent/docker-build-push@v6
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.event.repository.name }}
        PACKAGE_NAME: isthatoutyet
        TAGS: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
        # PUSH_IMAGE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        PUSH_IMAGE: true # We are always pushing the image to the registry, because will use are tagging non main branches with dev
        PRODUCTION: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.TAGS }}
        registry: ${{ env.REGISTRY }}
        pushImage: ${{ env.PUSH_IMAGE }}
        multiPlatform: false
        platform: linux/amd64
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PACKAGE_TOKEN }}
    
  update_web_server:
    runs-on: ubuntu-latest
    needs: push_to_registry
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Update the web server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} './update-server.sh'
