name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/my-image:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/my-image:latest

      - name: Run tests
        run: |
          docker run --rm ghcr.io/matthewglenn/isthatoutyet:latest /bin/sh -c "pytest tests"

      - name: Update README with build status
        run: |
          BUILD_STATUS=$(curl -s https://github.com/MatthewGlenn/isthatoutyet/actions/workflows/docker-image.yml/badge.svg?branch=main)
          sed -i "s|!\[Build Status\](.*)|![Build Status]($BUILD_STATUS)|" README.md
