name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Upload the Docker image to the container registry
      id: container_registry_upload
      uses: mr-smithers-excellent/docker-build-push@v6
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.event.repository.name }}
        PACKAGE_NAME: isthatoutyet
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: v1, latest
        registry: ${{ env.REGISTRY }}
        # pushImage: ${{ needs.check_version_latest.outputs.PUSH_IMAGE }}
        pushImage: true
        multiPlatform: false
        platform: linux/amd64
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PACKAGE_TOKEN }}

  update_status:
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Update README with build status
        run: |
          BUILD_STATUS=$(curl -s https://github.com/MatthewGlenn/isthatoutyet/actions/workflows/docker-image.yml/badge.svg?branch=main)
          sed -i "s|!\[Build Status\](.*)|![Build Status]($BUILD_STATUS)|" README.md